# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sim_ddd_cpp <- function(la, mu, K, max_t, num_species, seed = -1L) {
    .Call(`_physim_sim_ddd_cpp`, la, mu, K, max_t, num_species, seed)
}

sim_pbd_cpp <- function(la0, mu0, la1, mu1, trans_rate, max_t, num_species, seed = -1L) {
    .Call(`_physim_sim_pbd_cpp`, la0, mu0, la1, mu1, trans_rate, max_t, num_species, seed)
}

